name: CommandEvents
version: ${project.version}
main: me.commandrod.events.Main
api-version: 1.16
authors: [ commandROD ]
description: Made for ActiveEvents
depend:
  - ActiveEvents
  - Multiverse-Core
commands:
  givecommanditem:
    description: Gives a player a Command item.
    usage: /gci <item> [player]
    aliases: gci
  getvalues:
    description: Gets values stored in a command item.
    usage: /getvalues [-m]
  updatecommanditem:
    description: Updates a Command for all players.
    usage: /uci <item>
    aliases: uci
  openshop:
    description: Opens a Command Shop for a player.
    usage: /openshop <shop> [player]
  rlcf:
    description: Reloads the configuration file.
    usage: /rlcf
  start:
